-- ============================================================================
-- Seed: states and LGAs
--
-- All 36 Nigerian states + FCT (37 rows), and all 774 LGAs nationally.
-- Reference data — see docs/project-plan.md section 3 and
-- supabase/seed/README.md for the sourcing/verification notes.
--
-- Re-runnable: guarded by ON CONFLICT against the unique constraints defined
-- in 0001_init.sql (states_name_key; lgas_state_name_key).
--
-- `code` is a self-picked short code (2-3 letters, one exception for FCT
-- which keeps its universally-used 3-letter abbreviation). `slug` backs the
-- /state/<slug> and /state/<slug>/lga/<slug> public pages.
-- ============================================================================

-- 001a: states
insert into public.states (name, code, slug) values
  ('Abia', 'AB', 'abia'),
  ('Adamawa', 'AD', 'adamawa'),
  ('Akwa Ibom', 'AK', 'akwa-ibom'),
  ('Anambra', 'AN', 'anambra'),
  ('Bauchi', 'BA', 'bauchi'),
  ('Bayelsa', 'BY', 'bayelsa'),
  ('Benue', 'BE', 'benue'),
  ('Borno', 'BO', 'borno'),
  ('Cross River', 'CR', 'cross-river'),
  ('Delta', 'DE', 'delta'),
  ('Ebonyi', 'EB', 'ebonyi'),
  ('Edo', 'ED', 'edo'),
  ('Ekiti', 'EK', 'ekiti'),
  ('Enugu', 'EN', 'enugu'),
  ('Gombe', 'GO', 'gombe'),
  ('Imo', 'IM', 'imo'),
  ('Jigawa', 'JI', 'jigawa'),
  ('Kaduna', 'KD', 'kaduna'),
  ('Kano', 'KN', 'kano'),
  ('Katsina', 'KT', 'katsina'),
  ('Kebbi', 'KE', 'kebbi'),
  ('Kogi', 'KO', 'kogi'),
  ('Kwara', 'KW', 'kwara'),
  ('Lagos', 'LA', 'lagos'),
  ('Nasarawa', 'NA', 'nasarawa'),
  ('Niger', 'NI', 'niger'),
  ('Ogun', 'OG', 'ogun'),
  ('Ondo', 'ON', 'ondo'),
  ('Osun', 'OS', 'osun'),
  ('Oyo', 'OY', 'oyo'),
  ('Plateau', 'PL', 'plateau'),
  ('Rivers', 'RI', 'rivers'),
  ('Sokoto', 'SO', 'sokoto'),
  ('Taraba', 'TA', 'taraba'),
  ('Yobe', 'YO', 'yobe'),
  ('Zamfara', 'ZA', 'zamfara'),
  ('Federal Capital Territory', 'FCT', 'fct')
on conflict (name) do nothing;

-- 001b: lgas
insert into public.lgas (state_id, name, slug)
select s.id, v.lga_name, v.slug
from (values
  ('Abia', 'Aba North', 'aba-north'),
  ('Abia', 'Aba South', 'aba-south'),
  ('Abia', 'Arochukwu', 'arochukwu'),
  ('Abia', 'Bende', 'bende'),
  ('Abia', 'Ikwuano', 'ikwuano'),
  ('Abia', 'Isiala Ngwa North', 'isiala-ngwa-north'),
  ('Abia', 'Isiala Ngwa South', 'isiala-ngwa-south'),
  ('Abia', 'Isuikwuato', 'isuikwuato'),
  ('Abia', 'Obi Ngwa', 'obi-ngwa'),
  ('Abia', 'Ohafia', 'ohafia'),
  ('Abia', 'Osisioma', 'osisioma'),
  ('Abia', 'Ugwunagbo', 'ugwunagbo'),
  ('Abia', 'Ukwa East', 'ukwa-east'),
  ('Abia', 'Ukwa West', 'ukwa-west'),
  ('Abia', 'Umuahia North', 'umuahia-north'),
  ('Abia', 'Umuahia South', 'umuahia-south'),
  ('Abia', 'Umu Nneochi', 'umu-nneochi'),
  ('Adamawa', 'Demsa', 'demsa'),
  ('Adamawa', 'Fufure', 'fufure'),
  ('Adamawa', 'Ganye', 'ganye'),
  ('Adamawa', 'Gayuk', 'gayuk'),
  ('Adamawa', 'Gombi', 'gombi'),
  ('Adamawa', 'Guyuk', 'guyuk'),
  ('Adamawa', 'Hong', 'hong'),
  ('Adamawa', 'Jada', 'jada'),
  ('Adamawa', 'Lamurde', 'lamurde'),
  ('Adamawa', 'Madagali', 'madagali'),
  ('Adamawa', 'Maiha', 'maiha'),
  ('Adamawa', 'Mayo Belwa', 'mayo-belwa'),
  ('Adamawa', 'Michika', 'michika'),
  ('Adamawa', 'Mubi North', 'mubi-north'),
  ('Adamawa', 'Mubi South', 'mubi-south'),
  ('Adamawa', 'Numan', 'numan'),
  ('Adamawa', 'Shelleng', 'shelleng'),
  ('Adamawa', 'Song', 'song'),
  ('Adamawa', 'Toungo', 'toungo'),
  ('Adamawa', 'Yola North', 'yola-north'),
  ('Adamawa', 'Yola South', 'yola-south'),
  ('Akwa Ibom', 'Abak', 'abak'),
  ('Akwa Ibom', 'Eastern Obolo', 'eastern-obolo'),
  ('Akwa Ibom', 'Eket', 'eket'),
  ('Akwa Ibom', 'Esit Eket', 'esit-eket'),
  ('Akwa Ibom', 'Essien Udim', 'essien-udim'),
  ('Akwa Ibom', 'Etim Ekpo', 'etim-ekpo'),
  ('Akwa Ibom', 'Etinan', 'etinan'),
  ('Akwa Ibom', 'Ibeno', 'ibeno'),
  ('Akwa Ibom', 'Ibesikpo Asutan', 'ibesikpo-asutan'),
  ('Akwa Ibom', 'Ibiono Ibom', 'ibiono-ibom'),
  ('Akwa Ibom', 'Ika', 'ika'),
  ('Akwa Ibom', 'Ikono', 'ikono'),
  ('Akwa Ibom', 'Ikot Abasi', 'ikot-abasi'),
  ('Akwa Ibom', 'Ikot Ekpene', 'ikot-ekpene'),
  ('Akwa Ibom', 'Ini', 'ini'),
  ('Akwa Ibom', 'Itu', 'itu'),
  ('Akwa Ibom', 'Mbo', 'mbo'),
  ('Akwa Ibom', 'Mkpat Enin', 'mkpat-enin'),
  ('Akwa Ibom', 'Nsit Atai', 'nsit-atai'),
  ('Akwa Ibom', 'Nsit Ibom', 'nsit-ibom'),
  ('Akwa Ibom', 'Nsit Ubium', 'nsit-ubium'),
  ('Akwa Ibom', 'Obot Akara', 'obot-akara'),
  ('Akwa Ibom', 'Okobo', 'okobo'),
  ('Akwa Ibom', 'Onna', 'onna'),
  ('Akwa Ibom', 'Oron', 'oron'),
  ('Akwa Ibom', 'Oruk Anam', 'oruk-anam'),
  ('Akwa Ibom', 'Udung Uko', 'udung-uko'),
  ('Akwa Ibom', 'Ukanafun', 'ukanafun'),
  ('Akwa Ibom', 'Uruan', 'uruan'),
  ('Akwa Ibom', 'Urue-Offong/Oruko', 'urue-offong-oruko'),
  ('Akwa Ibom', 'Uyo', 'uyo'),
  ('Anambra', 'Aguata', 'aguata'),
  ('Anambra', 'Anambra East', 'anambra-east'),
  ('Anambra', 'Anambra West', 'anambra-west'),
  ('Anambra', 'Anaocha', 'anaocha'),
  ('Anambra', 'Awka North', 'awka-north'),
  ('Anambra', 'Awka South', 'awka-south'),
  ('Anambra', 'Ayamelum', 'ayamelum'),
  ('Anambra', 'Dunukofia', 'dunukofia'),
  ('Anambra', 'Ekwusigo', 'ekwusigo'),
  ('Anambra', 'Idemili North', 'idemili-north'),
  ('Anambra', 'Idemili South', 'idemili-south'),
  ('Anambra', 'Ihiala', 'ihiala'),
  ('Anambra', 'Njikoka', 'njikoka'),
  ('Anambra', 'Nnewi North', 'nnewi-north'),
  ('Anambra', 'Nnewi South', 'nnewi-south'),
  ('Anambra', 'Ogbaru', 'ogbaru'),
  ('Anambra', 'Onitsha North', 'onitsha-north'),
  ('Anambra', 'Onitsha South', 'onitsha-south'),
  ('Anambra', 'Orumba North', 'orumba-north'),
  ('Anambra', 'Orumba South', 'orumba-south'),
  ('Anambra', 'Oyi', 'oyi'),
  ('Bauchi', 'Alkaleri', 'alkaleri'),
  ('Bauchi', 'Bauchi', 'bauchi'),
  ('Bauchi', 'Bogoro', 'bogoro'),
  ('Bauchi', 'Damban', 'damban'),
  ('Bauchi', 'Darazo', 'darazo'),
  ('Bauchi', 'Dass', 'dass'),
  ('Bauchi', 'Gamawa', 'gamawa'),
  ('Bauchi', 'Ganjuwa', 'ganjuwa'),
  ('Bauchi', 'Giade', 'giade'),
  ('Bauchi', 'Itas/Gadau', 'itas-gadau'),
  ('Bauchi', 'Jama''are', 'jamaare'),
  ('Bauchi', 'Katagum', 'katagum'),
  ('Bauchi', 'Kirfi', 'kirfi'),
  ('Bauchi', 'Misau', 'misau'),
  ('Bauchi', 'Ningi', 'ningi'),
  ('Bauchi', 'Shira', 'shira'),
  ('Bauchi', 'Tafawa Balewa', 'tafawa-balewa'),
  ('Bauchi', 'Toro', 'toro'),
  ('Bauchi', 'Warji', 'warji'),
  ('Bauchi', 'Zaki', 'zaki'),
  ('Bayelsa', 'Brass', 'brass'),
  ('Bayelsa', 'Ekeremor', 'ekeremor'),
  ('Bayelsa', 'Kolokuma/Opokuma', 'kolokuma-opokuma'),
  ('Bayelsa', 'Nembe', 'nembe'),
  ('Bayelsa', 'Ogbia', 'ogbia'),
  ('Bayelsa', 'Sagbama', 'sagbama'),
  ('Bayelsa', 'Southern Ijaw', 'southern-ijaw'),
  ('Bayelsa', 'Yenagoa', 'yenagoa'),
  ('Benue', 'Ado', 'ado'),
  ('Benue', 'Agatu', 'agatu'),
  ('Benue', 'Apa', 'apa'),
  ('Benue', 'Buruku', 'buruku'),
  ('Benue', 'Gboko', 'gboko'),
  ('Benue', 'Guma', 'guma'),
  ('Benue', 'Gwer East', 'gwer-east'),
  ('Benue', 'Gwer West', 'gwer-west'),
  ('Benue', 'Katsina-Ala', 'katsina-ala'),
  ('Benue', 'Konshisha', 'konshisha'),
  ('Benue', 'Kwande', 'kwande'),
  ('Benue', 'Logo', 'logo'),
  ('Benue', 'Makurdi', 'makurdi'),
  ('Benue', 'Obi', 'obi'),
  ('Benue', 'Ogbadibo', 'ogbadibo'),
  ('Benue', 'Ohimini', 'ohimini'),
  ('Benue', 'Oju', 'oju'),
  ('Benue', 'Okpokwu', 'okpokwu'),
  ('Benue', 'Otukpo', 'otukpo'),
  ('Benue', 'Tarka', 'tarka'),
  ('Benue', 'Ukum', 'ukum'),
  ('Benue', 'Ushongo', 'ushongo'),
  ('Benue', 'Vandeikya', 'vandeikya'),
  ('Borno', 'Abadam', 'abadam'),
  ('Borno', 'Askira/Uba', 'askira-uba'),
  ('Borno', 'Bama', 'bama'),
  ('Borno', 'Bayo', 'bayo'),
  ('Borno', 'Biu', 'biu'),
  ('Borno', 'Chibok', 'chibok'),
  ('Borno', 'Damboa', 'damboa'),
  ('Borno', 'Dikwa', 'dikwa'),
  ('Borno', 'Gubio', 'gubio'),
  ('Borno', 'Guzamala', 'guzamala'),
  ('Borno', 'Gwoza', 'gwoza'),
  ('Borno', 'Hawul', 'hawul'),
  ('Borno', 'Jere', 'jere'),
  ('Borno', 'Kaga', 'kaga'),
  ('Borno', 'Kala/Balge', 'kala-balge'),
  ('Borno', 'Konduga', 'konduga'),
  ('Borno', 'Kukawa', 'kukawa'),
  ('Borno', 'Kwaya Kusar', 'kwaya-kusar'),
  ('Borno', 'Mafa', 'mafa'),
  ('Borno', 'Magumeri', 'magumeri'),
  ('Borno', 'Maiduguri', 'maiduguri'),
  ('Borno', 'Marte', 'marte'),
  ('Borno', 'Mobbar', 'mobbar'),
  ('Borno', 'Monguno', 'monguno'),
  ('Borno', 'Ngala', 'ngala'),
  ('Borno', 'Nganzai', 'nganzai'),
  ('Borno', 'Shani', 'shani'),
  ('Cross River', 'Abi', 'abi'),
  ('Cross River', 'Akamkpa', 'akamkpa'),
  ('Cross River', 'Akpabuyo', 'akpabuyo'),
  ('Cross River', 'Bakassi', 'bakassi'),
  ('Cross River', 'Bekwarra', 'bekwarra'),
  ('Cross River', 'Biase', 'biase'),
  ('Cross River', 'Boki', 'boki'),
  ('Cross River', 'Calabar Municipal', 'calabar-municipal'),
  ('Cross River', 'Calabar South', 'calabar-south'),
  ('Cross River', 'Etung', 'etung'),
  ('Cross River', 'Ikom', 'ikom'),
  ('Cross River', 'Obanliku', 'obanliku'),
  ('Cross River', 'Obubra', 'obubra'),
  ('Cross River', 'Obudu', 'obudu'),
  ('Cross River', 'Odukpani', 'odukpani'),
  ('Cross River', 'Ogoja', 'ogoja'),
  ('Cross River', 'Yakuur', 'yakuur'),
  ('Cross River', 'Yala', 'yala'),
  ('Delta', 'Aniocha North', 'aniocha-north'),
  ('Delta', 'Aniocha South', 'aniocha-south'),
  ('Delta', 'Bomadi', 'bomadi'),
  ('Delta', 'Burutu', 'burutu'),
  ('Delta', 'Ethiope East', 'ethiope-east'),
  ('Delta', 'Ethiope West', 'ethiope-west'),
  ('Delta', 'Ika North East', 'ika-north-east'),
  ('Delta', 'Ika South', 'ika-south'),
  ('Delta', 'Isoko North', 'isoko-north'),
  ('Delta', 'Isoko South', 'isoko-south'),
  ('Delta', 'Ndokwa East', 'ndokwa-east'),
  ('Delta', 'Ndokwa West', 'ndokwa-west'),
  ('Delta', 'Okpe', 'okpe'),
  ('Delta', 'Oshimili North', 'oshimili-north'),
  ('Delta', 'Oshimili South', 'oshimili-south'),
  ('Delta', 'Patani', 'patani'),
  ('Delta', 'Sapele', 'sapele'),
  ('Delta', 'Udu', 'udu'),
  ('Delta', 'Ughelli North', 'ughelli-north'),
  ('Delta', 'Ughelli South', 'ughelli-south'),
  ('Delta', 'Ukwuani', 'ukwuani'),
  ('Delta', 'Uvwie', 'uvwie'),
  ('Delta', 'Warri North', 'warri-north'),
  ('Delta', 'Warri South', 'warri-south'),
  ('Delta', 'Warri South West', 'warri-south-west'),
  ('Ebonyi', 'Abakaliki', 'abakaliki'),
  ('Ebonyi', 'Afikpo North', 'afikpo-north'),
  ('Ebonyi', 'Afikpo South', 'afikpo-south'),
  ('Ebonyi', 'Ebonyi', 'ebonyi'),
  ('Ebonyi', 'Ezza North', 'ezza-north'),
  ('Ebonyi', 'Ezza South', 'ezza-south'),
  ('Ebonyi', 'Ikwo', 'ikwo'),
  ('Ebonyi', 'Ishielu', 'ishielu'),
  ('Ebonyi', 'Ivo', 'ivo'),
  ('Ebonyi', 'Izzi', 'izzi'),
  ('Ebonyi', 'Ohaozara', 'ohaozara'),
  ('Ebonyi', 'Ohaukwu', 'ohaukwu'),
  ('Ebonyi', 'Onicha', 'onicha'),
  ('Edo', 'Akoko-Edo', 'akoko-edo'),
  ('Edo', 'Egor', 'egor'),
  ('Edo', 'Esan Central', 'esan-central'),
  ('Edo', 'Esan North-East', 'esan-north-east'),
  ('Edo', 'Esan South-East', 'esan-south-east'),
  ('Edo', 'Esan West', 'esan-west'),
  ('Edo', 'Etsako Central', 'etsako-central'),
  ('Edo', 'Etsako East', 'etsako-east'),
  ('Edo', 'Etsako West', 'etsako-west'),
  ('Edo', 'Igueben', 'igueben'),
  ('Edo', 'Ikpoba-Okha', 'ikpoba-okha'),
  ('Edo', 'Orhionmwon', 'orhionmwon'),
  ('Edo', 'Oredo', 'oredo'),
  ('Edo', 'Ovia North-East', 'ovia-north-east'),
  ('Edo', 'Ovia South-West', 'ovia-south-west'),
  ('Edo', 'Owan East', 'owan-east'),
  ('Edo', 'Owan West', 'owan-west'),
  ('Edo', 'Uhunmwonde', 'uhunmwonde'),
  ('Ekiti', 'Ado Ekiti', 'ado-ekiti'),
  ('Ekiti', 'Efon', 'efon'),
  ('Ekiti', 'Ekiti East', 'ekiti-east'),
  ('Ekiti', 'Ekiti South-West', 'ekiti-south-west'),
  ('Ekiti', 'Ekiti West', 'ekiti-west'),
  ('Ekiti', 'Emure', 'emure'),
  ('Ekiti', 'Gbonyin', 'gbonyin'),
  ('Ekiti', 'Ido Osi', 'ido-osi'),
  ('Ekiti', 'Ijero', 'ijero'),
  ('Ekiti', 'Ikere', 'ikere'),
  ('Ekiti', 'Ikole', 'ikole'),
  ('Ekiti', 'Ilejemeje', 'ilejemeje'),
  ('Ekiti', 'Irepodun/Ifelodun', 'irepodun-ifelodun'),
  ('Ekiti', 'Ise/Orun', 'ise-orun'),
  ('Ekiti', 'Moba', 'moba'),
  ('Ekiti', 'Oye', 'oye'),
  ('Enugu', 'Aninri', 'aninri'),
  ('Enugu', 'Awgu', 'awgu'),
  ('Enugu', 'Enugu East', 'enugu-east'),
  ('Enugu', 'Enugu North', 'enugu-north'),
  ('Enugu', 'Enugu South', 'enugu-south'),
  ('Enugu', 'Ezeagu', 'ezeagu'),
  ('Enugu', 'Igbo Etiti', 'igbo-etiti'),
  ('Enugu', 'Igbo Eze North', 'igbo-eze-north'),
  ('Enugu', 'Igbo Eze South', 'igbo-eze-south'),
  ('Enugu', 'Isi Uzo', 'isi-uzo'),
  ('Enugu', 'Nkanu East', 'nkanu-east'),
  ('Enugu', 'Nkanu West', 'nkanu-west'),
  ('Enugu', 'Nsukka', 'nsukka'),
  ('Enugu', 'Oji River', 'oji-river'),
  ('Enugu', 'Udenu', 'udenu'),
  ('Enugu', 'Udi', 'udi'),
  ('Enugu', 'Uzo Uwani', 'uzo-uwani'),
  ('Gombe', 'Akko', 'akko'),
  ('Gombe', 'Balanga', 'balanga'),
  ('Gombe', 'Billiri', 'billiri'),
  ('Gombe', 'Dukku', 'dukku'),
  ('Gombe', 'Funakaye', 'funakaye'),
  ('Gombe', 'Gombe', 'gombe'),
  ('Gombe', 'Kaltungo', 'kaltungo'),
  ('Gombe', 'Kwami', 'kwami'),
  ('Gombe', 'Nafada', 'nafada'),
  ('Gombe', 'Shongom', 'shongom'),
  ('Gombe', 'Yamaltu/Deba', 'yamaltu-deba'),
  ('Imo', 'Aboh Mbaise', 'aboh-mbaise'),
  ('Imo', 'Ahiazu Mbaise', 'ahiazu-mbaise'),
  ('Imo', 'Ehime Mbano', 'ehime-mbano'),
  ('Imo', 'Ezinihitte', 'ezinihitte'),
  ('Imo', 'Ideato North', 'ideato-north'),
  ('Imo', 'Ideato South', 'ideato-south'),
  ('Imo', 'Ihitte/Uboma', 'ihitte-uboma'),
  ('Imo', 'Ikeduru', 'ikeduru'),
  ('Imo', 'Isiala Mbano', 'isiala-mbano'),
  ('Imo', 'Isu', 'isu'),
  ('Imo', 'Mbaitoli', 'mbaitoli'),
  ('Imo', 'Ngor Okpala', 'ngor-okpala'),
  ('Imo', 'Njaba', 'njaba'),
  ('Imo', 'Nkwerre', 'nkwerre'),
  ('Imo', 'Nwangele', 'nwangele'),
  ('Imo', 'Obowo', 'obowo'),
  ('Imo', 'Oguta', 'oguta'),
  ('Imo', 'Ohaji/Egbema', 'ohaji-egbema'),
  ('Imo', 'Okigwe', 'okigwe'),
  ('Imo', 'Orlu', 'orlu'),
  ('Imo', 'Orsu', 'orsu'),
  ('Imo', 'Oru East', 'oru-east'),
  ('Imo', 'Oru West', 'oru-west'),
  ('Imo', 'Owerri Municipal', 'owerri-municipal'),
  ('Imo', 'Owerri North', 'owerri-north'),
  ('Imo', 'Owerri West', 'owerri-west'),
  ('Imo', 'Unuimo', 'unuimo'),
  ('Jigawa', 'Auyo', 'auyo'),
  ('Jigawa', 'Babura', 'babura'),
  ('Jigawa', 'Biriniwa', 'biriniwa'),
  ('Jigawa', 'Birnin Kudu', 'birnin-kudu'),
  ('Jigawa', 'Buji', 'buji'),
  ('Jigawa', 'Dutse', 'dutse'),
  ('Jigawa', 'Gagarawa', 'gagarawa'),
  ('Jigawa', 'Garki', 'garki'),
  ('Jigawa', 'Gumel', 'gumel'),
  ('Jigawa', 'Guri', 'guri'),
  ('Jigawa', 'Gwaram', 'gwaram'),
  ('Jigawa', 'Gwiwa', 'gwiwa'),
  ('Jigawa', 'Hadejia', 'hadejia'),
  ('Jigawa', 'Jahun', 'jahun'),
  ('Jigawa', 'Kafin Hausa', 'kafin-hausa'),
  ('Jigawa', 'Kaugama', 'kaugama'),
  ('Jigawa', 'Kazaure', 'kazaure'),
  ('Jigawa', 'Kiri Kasama', 'kiri-kasama'),
  ('Jigawa', 'Kiyawa', 'kiyawa'),
  ('Jigawa', 'Maigatari', 'maigatari'),
  ('Jigawa', 'Malam Madori', 'malam-madori'),
  ('Jigawa', 'Miga', 'miga'),
  ('Jigawa', 'Ringim', 'ringim'),
  ('Jigawa', 'Roni', 'roni'),
  ('Jigawa', 'Sule Tankarkar', 'sule-tankarkar'),
  ('Jigawa', 'Taura', 'taura'),
  ('Jigawa', 'Yankwashi', 'yankwashi'),
  ('Kaduna', 'Birnin Gwari', 'birnin-gwari'),
  ('Kaduna', 'Chikun', 'chikun'),
  ('Kaduna', 'Giwa', 'giwa'),
  ('Kaduna', 'Igabi', 'igabi'),
  ('Kaduna', 'Ikara', 'ikara'),
  ('Kaduna', 'Jaba', 'jaba'),
  ('Kaduna', 'Jema''a', 'jemaa'),
  ('Kaduna', 'Kachia', 'kachia'),
  ('Kaduna', 'Kaduna North', 'kaduna-north'),
  ('Kaduna', 'Kaduna South', 'kaduna-south'),
  ('Kaduna', 'Kagarko', 'kagarko'),
  ('Kaduna', 'Kajuru', 'kajuru'),
  ('Kaduna', 'Kaura', 'kaura'),
  ('Kaduna', 'Kauru', 'kauru'),
  ('Kaduna', 'Kubau', 'kubau'),
  ('Kaduna', 'Kudan', 'kudan'),
  ('Kaduna', 'Lere', 'lere'),
  ('Kaduna', 'Makarfi', 'makarfi'),
  ('Kaduna', 'Sabon Gari', 'sabon-gari'),
  ('Kaduna', 'Sanga', 'sanga'),
  ('Kaduna', 'Soba', 'soba'),
  ('Kaduna', 'Zangon Kataf', 'zangon-kataf'),
  ('Kaduna', 'Zaria', 'zaria'),
  ('Kano', 'Ajingi', 'ajingi'),
  ('Kano', 'Albasu', 'albasu'),
  ('Kano', 'Bagwai', 'bagwai'),
  ('Kano', 'Bebeji', 'bebeji'),
  ('Kano', 'Bichi', 'bichi'),
  ('Kano', 'Bunkure', 'bunkure'),
  ('Kano', 'Dala', 'dala'),
  ('Kano', 'Dambatta', 'dambatta'),
  ('Kano', 'Dawakin Kudu', 'dawakin-kudu'),
  ('Kano', 'Dawakin Tofa', 'dawakin-tofa'),
  ('Kano', 'Doguwa', 'doguwa'),
  ('Kano', 'Fagge', 'fagge'),
  ('Kano', 'Gabasawa', 'gabasawa'),
  ('Kano', 'Garko', 'garko'),
  ('Kano', 'Garun Mallam', 'garun-mallam'),
  ('Kano', 'Gaya', 'gaya'),
  ('Kano', 'Gezawa', 'gezawa'),
  ('Kano', 'Gwale', 'gwale'),
  ('Kano', 'Gwarzo', 'gwarzo'),
  ('Kano', 'Kabo', 'kabo'),
  ('Kano', 'Kano Municipal', 'kano-municipal'),
  ('Kano', 'Karaye', 'karaye'),
  ('Kano', 'Kibiya', 'kibiya'),
  ('Kano', 'Kiru', 'kiru'),
  ('Kano', 'Kumbotso', 'kumbotso'),
  ('Kano', 'Kunchi', 'kunchi'),
  ('Kano', 'Kura', 'kura'),
  ('Kano', 'Madobi', 'madobi'),
  ('Kano', 'Makoda', 'makoda'),
  ('Kano', 'Minjibir', 'minjibir'),
  ('Kano', 'Nasarawa', 'nasarawa'),
  ('Kano', 'Rano', 'rano'),
  ('Kano', 'Rimin Gado', 'rimin-gado'),
  ('Kano', 'Rogo', 'rogo'),
  ('Kano', 'Shanono', 'shanono'),
  ('Kano', 'Sumaila', 'sumaila'),
  ('Kano', 'Takai', 'takai'),
  ('Kano', 'Tarauni', 'tarauni'),
  ('Kano', 'Tofa', 'tofa'),
  ('Kano', 'Tsanyawa', 'tsanyawa'),
  ('Kano', 'Tudun Wada', 'tudun-wada'),
  ('Kano', 'Ungogo', 'ungogo'),
  ('Kano', 'Warawa', 'warawa'),
  ('Kano', 'Wudil', 'wudil'),
  ('Katsina', 'Bakori', 'bakori'),
  ('Katsina', 'Batagarawa', 'batagarawa'),
  ('Katsina', 'Batsari', 'batsari'),
  ('Katsina', 'Baure', 'baure'),
  ('Katsina', 'Bindawa', 'bindawa'),
  ('Katsina', 'Charanchi', 'charanchi'),
  ('Katsina', 'Dan Musa', 'dan-musa'),
  ('Katsina', 'Dandume', 'dandume'),
  ('Katsina', 'Danja', 'danja'),
  ('Katsina', 'Daura', 'daura'),
  ('Katsina', 'Dutsi', 'dutsi'),
  ('Katsina', 'Dutsin-Ma', 'dutsin-ma'),
  ('Katsina', 'Faskari', 'faskari'),
  ('Katsina', 'Funtua', 'funtua'),
  ('Katsina', 'Ingawa', 'ingawa'),
  ('Katsina', 'Jibia', 'jibia'),
  ('Katsina', 'Kafur', 'kafur'),
  ('Katsina', 'Kaita', 'kaita'),
  ('Katsina', 'Kankara', 'kankara'),
  ('Katsina', 'Kankia', 'kankia'),
  ('Katsina', 'Katsina', 'katsina'),
  ('Katsina', 'Kurfi', 'kurfi'),
  ('Katsina', 'Kusada', 'kusada'),
  ('Katsina', 'Mai''Adua', 'maiadua'),
  ('Katsina', 'Malumfashi', 'malumfashi'),
  ('Katsina', 'Mani', 'mani'),
  ('Katsina', 'Mashi', 'mashi'),
  ('Katsina', 'Matazu', 'matazu'),
  ('Katsina', 'Musawa', 'musawa'),
  ('Katsina', 'Rimi', 'rimi'),
  ('Katsina', 'Sabuwa', 'sabuwa'),
  ('Katsina', 'Safana', 'safana'),
  ('Katsina', 'Sandamu', 'sandamu'),
  ('Katsina', 'Zango', 'zango'),
  ('Kebbi', 'Aleiro', 'aleiro'),
  ('Kebbi', 'Arewa Dandi', 'arewa-dandi'),
  ('Kebbi', 'Argungu', 'argungu'),
  ('Kebbi', 'Augie', 'augie'),
  ('Kebbi', 'Bagudo', 'bagudo'),
  ('Kebbi', 'Birnin Kebbi', 'birnin-kebbi'),
  ('Kebbi', 'Bunza', 'bunza'),
  ('Kebbi', 'Dandi', 'dandi'),
  ('Kebbi', 'Fakai', 'fakai'),
  ('Kebbi', 'Gwandu', 'gwandu'),
  ('Kebbi', 'Jega', 'jega'),
  ('Kebbi', 'Kalgo', 'kalgo'),
  ('Kebbi', 'Koko/Besse', 'koko-besse'),
  ('Kebbi', 'Maiyama', 'maiyama'),
  ('Kebbi', 'Ngaski', 'ngaski'),
  ('Kebbi', 'Sakaba', 'sakaba'),
  ('Kebbi', 'Shanga', 'shanga'),
  ('Kebbi', 'Suru', 'suru'),
  ('Kebbi', 'Wasagu/Danko', 'wasagu-danko'),
  ('Kebbi', 'Yauri', 'yauri'),
  ('Kebbi', 'Zuru', 'zuru'),
  ('Kogi', 'Adavi', 'adavi'),
  ('Kogi', 'Ajaokuta', 'ajaokuta'),
  ('Kogi', 'Ankpa', 'ankpa'),
  ('Kogi', 'Bassa', 'bassa'),
  ('Kogi', 'Dekina', 'dekina'),
  ('Kogi', 'Ibaji', 'ibaji'),
  ('Kogi', 'Idah', 'idah'),
  ('Kogi', 'Igalamela Odolu', 'igalamela-odolu'),
  ('Kogi', 'Ijumu', 'ijumu'),
  ('Kogi', 'Kabba/Bunu', 'kabba-bunu'),
  ('Kogi', 'Kogi', 'kogi'),
  ('Kogi', 'Lokoja', 'lokoja'),
  ('Kogi', 'Mopa Muro', 'mopa-muro'),
  ('Kogi', 'Ofu', 'ofu'),
  ('Kogi', 'Ogori/Magongo', 'ogori-magongo'),
  ('Kogi', 'Okehi', 'okehi'),
  ('Kogi', 'Okene', 'okene'),
  ('Kogi', 'Olamaboro', 'olamaboro'),
  ('Kogi', 'Omala', 'omala'),
  ('Kogi', 'Yagba East', 'yagba-east'),
  ('Kogi', 'Yagba West', 'yagba-west'),
  ('Kwara', 'Asa', 'asa'),
  ('Kwara', 'Baruten', 'baruten'),
  ('Kwara', 'Edu', 'edu'),
  ('Kwara', 'Ekiti', 'ekiti'),
  ('Kwara', 'Ifelodun', 'ifelodun'),
  ('Kwara', 'Ilorin East', 'ilorin-east'),
  ('Kwara', 'Ilorin South', 'ilorin-south'),
  ('Kwara', 'Ilorin West', 'ilorin-west'),
  ('Kwara', 'Irepodun', 'irepodun'),
  ('Kwara', 'Isin', 'isin'),
  ('Kwara', 'Kaiama', 'kaiama'),
  ('Kwara', 'Moro', 'moro'),
  ('Kwara', 'Offa', 'offa'),
  ('Kwara', 'Oke Ero', 'oke-ero'),
  ('Kwara', 'Oyun', 'oyun'),
  ('Kwara', 'Pategi', 'pategi'),
  ('Lagos', 'Agege', 'agege'),
  ('Lagos', 'Ajeromi-Ifelodun', 'ajeromi-ifelodun'),
  ('Lagos', 'Alimosho', 'alimosho'),
  ('Lagos', 'Amuwo-Odofin', 'amuwo-odofin'),
  ('Lagos', 'Apapa', 'apapa'),
  ('Lagos', 'Badagry', 'badagry'),
  ('Lagos', 'Epe', 'epe'),
  ('Lagos', 'Eti Osa', 'eti-osa'),
  ('Lagos', 'Ibeju-Lekki', 'ibeju-lekki'),
  ('Lagos', 'Ifako-Ijaiye', 'ifako-ijaiye'),
  ('Lagos', 'Ikeja', 'ikeja'),
  ('Lagos', 'Ikorodu', 'ikorodu'),
  ('Lagos', 'Kosofe', 'kosofe'),
  ('Lagos', 'Lagos Island', 'lagos-island'),
  ('Lagos', 'Lagos Mainland', 'lagos-mainland'),
  ('Lagos', 'Mushin', 'mushin'),
  ('Lagos', 'Ojo', 'ojo'),
  ('Lagos', 'Oshodi-Isolo', 'oshodi-isolo'),
  ('Lagos', 'Shomolu', 'shomolu'),
  ('Lagos', 'Surulere', 'surulere'),
  ('Nasarawa', 'Akwanga', 'akwanga'),
  ('Nasarawa', 'Awe', 'awe'),
  ('Nasarawa', 'Doma', 'doma'),
  ('Nasarawa', 'Karu', 'karu'),
  ('Nasarawa', 'Keana', 'keana'),
  ('Nasarawa', 'Keffi', 'keffi'),
  ('Nasarawa', 'Kokona', 'kokona'),
  ('Nasarawa', 'Lafia', 'lafia'),
  ('Nasarawa', 'Nasarawa', 'nasarawa'),
  ('Nasarawa', 'Nasarawa Egon', 'nasarawa-egon'),
  ('Nasarawa', 'Obi', 'obi'),
  ('Nasarawa', 'Toto', 'toto'),
  ('Nasarawa', 'Wamba', 'wamba'),
  ('Niger', 'Agaie', 'agaie'),
  ('Niger', 'Agwara', 'agwara'),
  ('Niger', 'Bida', 'bida'),
  ('Niger', 'Borgu', 'borgu'),
  ('Niger', 'Bosso', 'bosso'),
  ('Niger', 'Chanchaga', 'chanchaga'),
  ('Niger', 'Edati', 'edati'),
  ('Niger', 'Gbako', 'gbako'),
  ('Niger', 'Gurara', 'gurara'),
  ('Niger', 'Katcha', 'katcha'),
  ('Niger', 'Kontagora', 'kontagora'),
  ('Niger', 'Lapai', 'lapai'),
  ('Niger', 'Lavun', 'lavun'),
  ('Niger', 'Magama', 'magama'),
  ('Niger', 'Mariga', 'mariga'),
  ('Niger', 'Mashegu', 'mashegu'),
  ('Niger', 'Mokwa', 'mokwa'),
  ('Niger', 'Moya', 'moya'),
  ('Niger', 'Paikoro', 'paikoro'),
  ('Niger', 'Rafi', 'rafi'),
  ('Niger', 'Rijau', 'rijau'),
  ('Niger', 'Shiroro', 'shiroro'),
  ('Niger', 'Suleja', 'suleja'),
  ('Niger', 'Tafa', 'tafa'),
  ('Niger', 'Wushishi', 'wushishi'),
  ('Ogun', 'Abeokuta North', 'abeokuta-north'),
  ('Ogun', 'Abeokuta South', 'abeokuta-south'),
  ('Ogun', 'Ado-Odo/Ota', 'ado-odo-ota'),
  ('Ogun', 'Ewekoro', 'ewekoro'),
  ('Ogun', 'Ifo', 'ifo'),
  ('Ogun', 'Ijebu East', 'ijebu-east'),
  ('Ogun', 'Ijebu North', 'ijebu-north'),
  ('Ogun', 'Ijebu North East', 'ijebu-north-east'),
  ('Ogun', 'Ijebu Ode', 'ijebu-ode'),
  ('Ogun', 'Ikenne', 'ikenne'),
  ('Ogun', 'Imeko Afon', 'imeko-afon'),
  ('Ogun', 'Ipokia', 'ipokia'),
  ('Ogun', 'Obafemi Owode', 'obafemi-owode'),
  ('Ogun', 'Odeda', 'odeda'),
  ('Ogun', 'Odogbolu', 'odogbolu'),
  ('Ogun', 'Ogun Waterside', 'ogun-waterside'),
  ('Ogun', 'Remo North', 'remo-north'),
  ('Ogun', 'Shagamu', 'shagamu'),
  ('Ogun', 'Yewa North', 'yewa-north'),
  ('Ogun', 'Yewa South', 'yewa-south'),
  ('Ondo', 'Akoko North-East', 'akoko-north-east'),
  ('Ondo', 'Akoko North-West', 'akoko-north-west'),
  ('Ondo', 'Akoko South-East', 'akoko-south-east'),
  ('Ondo', 'Akoko South-West', 'akoko-south-west'),
  ('Ondo', 'Akure North', 'akure-north'),
  ('Ondo', 'Akure South', 'akure-south'),
  ('Ondo', 'Ese Odo', 'ese-odo'),
  ('Ondo', 'Idanre', 'idanre'),
  ('Ondo', 'Ifedore', 'ifedore'),
  ('Ondo', 'Ilaje', 'ilaje'),
  ('Ondo', 'Ile Oluji/Okeigbo', 'ile-oluji-okeigbo'),
  ('Ondo', 'Irele', 'irele'),
  ('Ondo', 'Odigbo', 'odigbo'),
  ('Ondo', 'Okitipupa', 'okitipupa'),
  ('Ondo', 'Ondo East', 'ondo-east'),
  ('Ondo', 'Ondo West', 'ondo-west'),
  ('Ondo', 'Ose', 'ose'),
  ('Ondo', 'Owo', 'owo'),
  ('Osun', 'Aiyedaade', 'aiyedaade'),
  ('Osun', 'Aiyedire', 'aiyedire'),
  ('Osun', 'Atakunmosa East', 'atakunmosa-east'),
  ('Osun', 'Atakunmosa West', 'atakunmosa-west'),
  ('Osun', 'Boluwaduro', 'boluwaduro'),
  ('Osun', 'Boripe', 'boripe'),
  ('Osun', 'Ede North', 'ede-north'),
  ('Osun', 'Ede South', 'ede-south'),
  ('Osun', 'Egbedore', 'egbedore'),
  ('Osun', 'Ejigbo', 'ejigbo'),
  ('Osun', 'Ife Central', 'ife-central'),
  ('Osun', 'Ife East', 'ife-east'),
  ('Osun', 'Ife North', 'ife-north'),
  ('Osun', 'Ife South', 'ife-south'),
  ('Osun', 'Ifedayo', 'ifedayo'),
  ('Osun', 'Ifelodun', 'ifelodun'),
  ('Osun', 'Ila', 'ila'),
  ('Osun', 'Ilesa East', 'ilesa-east'),
  ('Osun', 'Ilesa West', 'ilesa-west'),
  ('Osun', 'Irepodun', 'irepodun'),
  ('Osun', 'Irewole', 'irewole'),
  ('Osun', 'Isokan', 'isokan'),
  ('Osun', 'Iwo', 'iwo'),
  ('Osun', 'Obokun', 'obokun'),
  ('Osun', 'Odo Otin', 'odo-otin'),
  ('Osun', 'Ola Oluwa', 'ola-oluwa'),
  ('Osun', 'Olorunda', 'olorunda'),
  ('Osun', 'Oriade', 'oriade'),
  ('Osun', 'Orolu', 'orolu'),
  ('Osun', 'Osogbo', 'osogbo'),
  ('Oyo', 'Afijio', 'afijio'),
  ('Oyo', 'Akinyele', 'akinyele'),
  ('Oyo', 'Atiba', 'atiba'),
  ('Oyo', 'Atisbo', 'atisbo'),
  ('Oyo', 'Egbeda', 'egbeda'),
  ('Oyo', 'Ibadan North', 'ibadan-north'),
  ('Oyo', 'Ibadan North-East', 'ibadan-north-east'),
  ('Oyo', 'Ibadan North-West', 'ibadan-north-west'),
  ('Oyo', 'Ibadan South-East', 'ibadan-south-east'),
  ('Oyo', 'Ibadan South-West', 'ibadan-south-west'),
  ('Oyo', 'Ibarapa Central', 'ibarapa-central'),
  ('Oyo', 'Ibarapa East', 'ibarapa-east'),
  ('Oyo', 'Ibarapa North', 'ibarapa-north'),
  ('Oyo', 'Ido', 'ido'),
  ('Oyo', 'Irepo', 'irepo'),
  ('Oyo', 'Iseyin', 'iseyin'),
  ('Oyo', 'Itesiwaju', 'itesiwaju'),
  ('Oyo', 'Iwajowa', 'iwajowa'),
  ('Oyo', 'Kajola', 'kajola'),
  ('Oyo', 'Lagelu', 'lagelu'),
  ('Oyo', 'Ogbomosho North', 'ogbomosho-north'),
  ('Oyo', 'Ogbomosho South', 'ogbomosho-south'),
  ('Oyo', 'Ogo Oluwa', 'ogo-oluwa'),
  ('Oyo', 'Olorunsogo', 'olorunsogo'),
  ('Oyo', 'Oluyole', 'oluyole'),
  ('Oyo', 'Ona Ara', 'ona-ara'),
  ('Oyo', 'Orelope', 'orelope'),
  ('Oyo', 'Ori Ire', 'ori-ire'),
  ('Oyo', 'Oyo East', 'oyo-east'),
  ('Oyo', 'Oyo West', 'oyo-west'),
  ('Oyo', 'Saki East', 'saki-east'),
  ('Oyo', 'Saki West', 'saki-west'),
  ('Oyo', 'Surulere', 'surulere'),
  ('Plateau', 'Bokkos', 'bokkos'),
  ('Plateau', 'Barkin Ladi', 'barkin-ladi'),
  ('Plateau', 'Bassa', 'bassa'),
  ('Plateau', 'Jos East', 'jos-east'),
  ('Plateau', 'Jos North', 'jos-north'),
  ('Plateau', 'Jos South', 'jos-south'),
  ('Plateau', 'Kanam', 'kanam'),
  ('Plateau', 'Kanke', 'kanke'),
  ('Plateau', 'Langtang North', 'langtang-north'),
  ('Plateau', 'Langtang South', 'langtang-south'),
  ('Plateau', 'Mangu', 'mangu'),
  ('Plateau', 'Mikang', 'mikang'),
  ('Plateau', 'Pankshin', 'pankshin'),
  ('Plateau', 'Qua''an Pan', 'quaan-pan'),
  ('Plateau', 'Riyom', 'riyom'),
  ('Plateau', 'Shendam', 'shendam'),
  ('Plateau', 'Wase', 'wase'),
  ('Rivers', 'Abua/Odual', 'abua-odual'),
  ('Rivers', 'Ahoada East', 'ahoada-east'),
  ('Rivers', 'Ahoada West', 'ahoada-west'),
  ('Rivers', 'Akuku-Toru', 'akuku-toru'),
  ('Rivers', 'Andoni', 'andoni'),
  ('Rivers', 'Asari-Toru', 'asari-toru'),
  ('Rivers', 'Bonny', 'bonny'),
  ('Rivers', 'Degema', 'degema'),
  ('Rivers', 'Eleme', 'eleme'),
  ('Rivers', 'Emuoha', 'emuoha'),
  ('Rivers', 'Etche', 'etche'),
  ('Rivers', 'Gokana', 'gokana'),
  ('Rivers', 'Ikwerre', 'ikwerre'),
  ('Rivers', 'Khana', 'khana'),
  ('Rivers', 'Obio/Akpor', 'obio-akpor'),
  ('Rivers', 'Ogba/Egbema/Ndoni', 'ogba-egbema-ndoni'),
  ('Rivers', 'Ogu/Bolo', 'ogu-bolo'),
  ('Rivers', 'Okrika', 'okrika'),
  ('Rivers', 'Omuma', 'omuma'),
  ('Rivers', 'Opobo/Nkoro', 'opobo-nkoro'),
  ('Rivers', 'Oyigbo', 'oyigbo'),
  ('Rivers', 'Port Harcourt', 'port-harcourt'),
  ('Rivers', 'Tai', 'tai'),
  ('Sokoto', 'Binji', 'binji'),
  ('Sokoto', 'Bodinga', 'bodinga'),
  ('Sokoto', 'Dange Shuni', 'dange-shuni'),
  ('Sokoto', 'Gada', 'gada'),
  ('Sokoto', 'Goronyo', 'goronyo'),
  ('Sokoto', 'Gudu', 'gudu'),
  ('Sokoto', 'Gwadabawa', 'gwadabawa'),
  ('Sokoto', 'Illela', 'illela'),
  ('Sokoto', 'Isa', 'isa'),
  ('Sokoto', 'Kebbe', 'kebbe'),
  ('Sokoto', 'Kware', 'kware'),
  ('Sokoto', 'Rabah', 'rabah'),
  ('Sokoto', 'Sabon Birni', 'sabon-birni'),
  ('Sokoto', 'Shagari', 'shagari'),
  ('Sokoto', 'Silame', 'silame'),
  ('Sokoto', 'Sokoto North', 'sokoto-north'),
  ('Sokoto', 'Sokoto South', 'sokoto-south'),
  ('Sokoto', 'Tambuwal', 'tambuwal'),
  ('Sokoto', 'Tangaza', 'tangaza'),
  ('Sokoto', 'Tureta', 'tureta'),
  ('Sokoto', 'Wamako', 'wamako'),
  ('Sokoto', 'Wurno', 'wurno'),
  ('Sokoto', 'Yabo', 'yabo'),
  ('Taraba', 'Ardo Kola', 'ardo-kola'),
  ('Taraba', 'Bali', 'bali'),
  ('Taraba', 'Donga', 'donga'),
  ('Taraba', 'Gashaka', 'gashaka'),
  ('Taraba', 'Gassol', 'gassol'),
  ('Taraba', 'Ibi', 'ibi'),
  ('Taraba', 'Jalingo', 'jalingo'),
  ('Taraba', 'Karim Lamido', 'karim-lamido'),
  ('Taraba', 'Kumi', 'kumi'),
  ('Taraba', 'Lau', 'lau'),
  ('Taraba', 'Sardauna', 'sardauna'),
  ('Taraba', 'Takum', 'takum'),
  ('Taraba', 'Ussa', 'ussa'),
  ('Taraba', 'Wukari', 'wukari'),
  ('Taraba', 'Yorro', 'yorro'),
  ('Taraba', 'Zing', 'zing'),
  ('Yobe', 'Bade', 'bade'),
  ('Yobe', 'Bursari', 'bursari'),
  ('Yobe', 'Damaturu', 'damaturu'),
  ('Yobe', 'Fika', 'fika'),
  ('Yobe', 'Fune', 'fune'),
  ('Yobe', 'Geidam', 'geidam'),
  ('Yobe', 'Gujba', 'gujba'),
  ('Yobe', 'Gulani', 'gulani'),
  ('Yobe', 'Jakusko', 'jakusko'),
  ('Yobe', 'Karasuwa', 'karasuwa'),
  ('Yobe', 'Machina', 'machina'),
  ('Yobe', 'Nangere', 'nangere'),
  ('Yobe', 'Nguru', 'nguru'),
  ('Yobe', 'Potiskum', 'potiskum'),
  ('Yobe', 'Tarmuwa', 'tarmuwa'),
  ('Yobe', 'Yunusari', 'yunusari'),
  ('Yobe', 'Yusufari', 'yusufari'),
  ('Zamfara', 'Anka', 'anka'),
  ('Zamfara', 'Bakura', 'bakura'),
  ('Zamfara', 'Birnin Magaji/Kiyaw', 'birnin-magaji-kiyaw'),
  ('Zamfara', 'Bukkuyum', 'bukkuyum'),
  ('Zamfara', 'Bungudu', 'bungudu'),
  ('Zamfara', 'Gummi', 'gummi'),
  ('Zamfara', 'Gusau', 'gusau'),
  ('Zamfara', 'Kaura Namoda', 'kaura-namoda'),
  ('Zamfara', 'Maradun', 'maradun'),
  ('Zamfara', 'Maru', 'maru'),
  ('Zamfara', 'Shinkafi', 'shinkafi'),
  ('Zamfara', 'Talata Mafara', 'talata-mafara'),
  ('Zamfara', 'Tsafe', 'tsafe'),
  ('Zamfara', 'Zurmi', 'zurmi'),
  ('Federal Capital Territory', 'Abaji', 'abaji'),
  ('Federal Capital Territory', 'Abuja Municipal', 'abuja-municipal'),
  ('Federal Capital Territory', 'Bwari', 'bwari'),
  ('Federal Capital Territory', 'Gwagwalada', 'gwagwalada'),
  ('Federal Capital Territory', 'Kuje', 'kuje'),
  ('Federal Capital Territory', 'Kwali', 'kwali')
) as v(state_name, lga_name, slug)
join public.states s on s.name = v.state_name
on conflict (state_id, name) do nothing;
